name: dartobjectutils
description: A Dart library designed to help safely extract values from untyped objects.
version: 0.1.2
repository: https://github.com/arran4/dartobjectutils

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.4
